server:
  port: 8080

spring:
  application:
    name: parking-lot-api
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG

jwt:
  secret: jwt-secret
  expiration: 10000
